name = "ximagine-2api-pro"
main = "worker.js"
compatibility_date = "2024-03-03"

[vars]
# ⚠️ 請在 Cloudflare 控制台或使用 `wrangler secret put API_MASTER_KEY` 設置此密鑰
API_MASTER_KEY = "1"

# [observability]
# enabled = true

# [[routes]]
# pattern = "your-domain.com"
# custom_domain = true
